import Footer from '@/components/Footer'
import Header from '@/components/Header'
import ProgressBar from '@/components/ProgressBar'
import { ClerkProvider } from '@clerk/nextjs'
import type { Metadata } from 'next'
import localFont from 'next/font/local'
import './globals.css'

const geistSans = localFont({
  src: './fonts/GeistVF.woff',
  variable: '--font-geist-sans',
  weight: '100 900',
})
const geistMono = localFont({
  src: './fonts/GeistMonoVF.woff',
  variable: '--font-geist-mono',
  weight: '100 900',
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

// TODO Fix responsive design (set a max-width)

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <ClerkProvider
      appearance={{
        elements: {
          userButtonOuterIdentifier:
            'max-w-[150px] truncate hidden text-zinc-800 dark:text-zinc-200 hover:text-zinc-600 dark:hover:text-zinc-100 3xs:inline-block',
          userButtonAvatarBox: 'w-5 h-5',
          userButtonBox:
            'h-5 transition-transform duration-200 active:scale-95',
        },
      }}
    >
      <html lang='en'>
        <body
          className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        >
          <ProgressBar />

          <Header />

          {/* NOTE: We are accounting for the Header height by adding padding at the top (so the Header can be fixed when scrolling) */}
          <main className='flex flex-col gap-4 px-4 pb-32 pt-[115px] 3xs:pt-[128px] 2xs:pt-[144px] xs:pt-[160px] sm:pt-[174px]'>
            {children}
          </main>

          <footer className='flex w-full flex-col flex-wrap items-center justify-center gap-2 border-t border-t-pink-500/10 bg-pink-400/10 p-4 text-sm dark:bg-pink-600/10'>
            <Footer />
          </footer>
        </body>
      </html>
    </ClerkProvider>
  )
}
